### ISSUE TITLE
Question on Segmentation task?

### ISSUE THREAD

**Issue by lannguyen0910** [kaylode/theseus#12]
Hey @kaylode, does the Theseus only support Binary Class Segmentation for now right? I try to use it but it returned an runtime error at dice loss, like this:
```
File "/content/main/theseus/segmentation/losses/dice_loss.py", line 37, in forward
    num = torch.sum(torch.mul(predict, target), dim=1) + self.smooth

RuntimeError: The size of tensor a (6750208) must match the size of tensor b (65536) at non-singleton dimension 1
```
Thanks!

**Comment by lannguyen0910** [comment]
Ah yes, i saw you're working on it 💯

**Comment by kaylode** [comment]
Ah yes. I'm working on multiclass segmentation right now. You can co-test  with me on the segmentation branch, it works fine for me on several datasets. But please note that you have to customize your own dataset and dataloader to read/ preprocess . The targets must be one-hot  encoded (B, num_classes, H, W) to be able to work with all the loss functions and metrics.

**Comment by lannguyen0910** [comment]
Okay, I'm testing it right now. Will you include coco dataset reader in the future. In coco format there's also a 'segmentation' part in 'annotation'. I think you may consider to support coco, as I saw there're still many datasets use it.

**Comment by kaylode** [comment]
Thanks for your opinion.  Most datasets use coco annotations for instance segmentation tasks. The current segmentation branch in this project supports only semantic tasks and semantic ground truth requires less information than instance task (only need a grayscale mask). But I will give it a thought later.
