### ISSUE TITLE
Possible issue with trainer

### ISSUE THREAD

**Issue by lannguyen0910** [kaylode/theseus#37]
Hi @kaylode, if you have time, could you update the notebooks (the config part)?
When tested, i encountered this error:
```python
Traceback (most recent call last):
  File "/content/main/configs/classification/train.py", line 10, in <module>
    train_pipeline.fit()
  File "/content/main/theseus/base/pipeline.py", line 237, in fit
    self.trainer.fit()
  File "/content/main/theseus/base/trainer/base_trainer.py", line 71, in fit
    self.training_epoch()
  File "/content/main/theseus/base/trainer/supervised_trainer.py", line 83, in training_epoch
    self.scaler(loss, self.optimizer)
TypeError: 'bool' object is not callable
```

So i think it might be problem with the ```scaler```, after changing ```use_fp16``` to True as default  in ```BaseTrainer```. It's runnable, like this:
```python
class BaseTrainer():
def __init__(self,
                use_fp16: bool = True, 
                ...
                ):
```
It doesn't work albeit i've already set the global ```use_fp16``` variable to True.
```
global:
  exp_name: null
  exist_ok: false
  debug: true
  cfg_transform: configs/classification/transform.yaml
  save_dir: /content/main/runs
  device: cuda:0
  use_fp16: true
  pretrained: null
  resume: null
```
 So i think it might be a possible issue. I notice that in ```SupervisedTrainer``` there isn't any catch for the ```scaler``` when we set False ```use_fp16```, therefore it can trigger this error ```TypeError: 'bool' object is not callable```

**Comment by kaylode** [comment]
Exactly, I have to read usage documentation of `torch.cuda.amp.GradScaler` again to correct this.
