### ISSUE TITLE
About master branch and detection branch

### ISSUE THREAD

**Issue by IricsDo** [kaylode/theseus#6]
Hello, Thanks your repo! It's very helpful for me. Again thanks for contribution.
I want to ask you about detection branch. Can you meger it into master branch or set it to master branch. I clone your repo to use, but it only master branch. And it miss alot of file. It's very difficut for me to run train.
I hope you do it soon as soon possible.
Have a nice day!

**Comment by kaylode** [comment]
Hi there,

To clone and use different branch, you can execute ```git checkout <branch-name>```.  Therefore, to switch to ```detection``` branch, simply call ```git checkout detection```
